name: ci-pr
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

env:
    IMAGE: ghcr.io/sii-scrna-seq/scrnaseq-standardised-pipeline:latest

jobs:
    smoke:
        runs-on: ubuntu-latest
        permissions:
            packages: read
            contents: read
        steps:
            - uses: actions/checkout@v4
            - name: Login to GHCR
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            - name: Pull runtime image
              run: docker pull $IMAGE
            - name: Prepare test inputs
              run: |
                for a in tests/*.tar.gz; do
                  echo "Extracting $a"
                  tar -xzf "$a" -C tests
                done
                echo "After extraction:"
                find tests -maxdepth 2 -type d -print
            - name: Run smoke test
              run: |
                docker run --rm \
                  -e RENV_CONFIG_AUTOLOADER_ENABLED=FALSE -e RENV_PROJECT=NULL \
                  -v "$PWD":/work \
                  ${{ env.IMAGE }} \
                  /work/tests
            - name: List outputs
              run: |
                find tests/ -maxdepth 1 -type f -print || true
